<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main page</title>
    <link rel="stylesheet" href="/css/main.css">
</head>
<body>
<nav id="topnav">
    <ul class="menu">
        <li><a href="/">Strona główna</a></li>
        <li><a href="/code/latest">Ostatnie</a></li>
        <li><a href="/code/new">Nowy kod</a></li>
        <li><a href="/code/">Znajdź</a></li>
    </ul>
</nav>
<div class="categories">
    <h1>Wpisz swój kod</h1>
    <p>Repozytorium v 0.1</p>
    <p>Tylko nie spam</p>
</div>
</body>
</html>
