<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Create</title>
    <link rel="stylesheet" href="/css/main.css">
    <script src="/js/send.js"></script>
</head>
<body>
    <textarea id="code_snippet" placeholder="This is example code {&#13;&#10   doing...&#13;&#10}"></textarea>
    <button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>
